
#[macro_use]
extern crate glium;
extern crate rand;
extern crate cgmath;
extern crate image;

mod model;
mod utils;
mod renderer;

use cgmath::{Point3, Vector3, Matrix4, Euler, deg, Quaternion, perspective};
use utils::load_shader;
use model::cube;
use renderer::context;


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

const WINDOW_WIDTH: u32 = 1920;
const WINDOW_HEIGHT: u32 = 1080;

fn main() {

    let window_ratio: f32 = WINDOW_WIDTH as f32 / WINDOW_HEIGHT as f32;

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    let mut ctx = context::Context::new(WINDOW_WIDTH, WINDOW_HEIGHT);

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    let vertex_shader = load_shader("geom.vs");
    let fragment_shader = load_shader("geom.fs");

    let program = match (vertex_shader, fragment_shader) {
        (Ok(a), Ok(b)) => glium::Program::from_source(ctx.display(), &a, &b, None).unwrap(),
        _ => panic!("could not find shaders"),
    };

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    let cube = cube::Cube::new(ctx.display()).unwrap();

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    let axis_plot = utils::Axis::new(ctx.display());

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    print!("load atlas:\n");
    let atlas = model::textures::load_atlas("test/atlas1").unwrap();
    let atlas_count = atlas.count;
    let atlas_side = atlas.side;
    let image_dimensions = atlas.image.dimensions();
    let image = glium::texture::RawImage2d::from_raw_rgba(atlas.image.into_raw(), image_dimensions);
    // let atlas_texture = glium::texture::Texture2d::new(ctx.display(), image).unwrap();
    let atlas_texture = glium::texture::Texture2d::with_mipmaps(ctx.display(), image,
                 glium::texture::MipmapsOption::AutoGeneratedMipmaps).unwrap();
    print!("loaded {} mipmaps:\n", atlas_texture.get_mipmap_levels());

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    // translations for the instances
    let size_x = 100;
    let size_z = 100;
    let mut translations: Vec<(f32, f32)> = Vec::new();
    for x in 0..size_x {
        for y in 0..size_z {
            translations.push((x as f32, y as f32));
        }
    }

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    // building the vertex buffer with the attributes per instance
    let instance_attr = {

        #[derive(Copy, Clone, Debug)]
        struct Attr {
            world_position: (f32, f32, f32),
            in_color: (f32, f32, f32),
            tex_offset: (f32, f32),
        }
        implement_vertex!(Attr, world_position, in_color, tex_offset);

        use rand::Rng;
        let mut rng = rand::thread_rng();

        let mut count = 0;
        let data = translations.iter()
            .map(|pos| {

                let tex_id = rng.gen_range(0, atlas_count);
                count += 1;
                let i_off = ((tex_id / atlas_side) as f32) / atlas_side as f32;
                let j_off = ((tex_id % atlas_side) as f32) / atlas_side as f32;

                //   print!("{}  {},{} @ {},{}\n", tex_id,
                //                                 (tex_id % atlas_side), (tex_id / atlas_side),
                //                                 i_off, j_off);

                Attr {
                    world_position: (pos.0, 0.0, pos.1),
                    in_color: (rand::random(), rand::random(), rand::random()),
                    tex_offset: (i_off as f32, j_off as f32),
                }
            })
            .collect::<Vec<_>>();

        glium::vertex::VertexBuffer::dynamic(ctx.display(), &data).unwrap()
    };
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    // generate camera...
    let view_eye: Point3<f32> = Point3::new(0.0, 20.0, -50.0);
    let view_center: Point3<f32> = Point3::new(0.0, 0.0, 0.0);

    let view_up: Vector3<f32> = Vector3::new(0.0, 1.0, 0.0);

    let perspective_matrix: Matrix4<f32> = perspective(deg(45.0), window_ratio, 0.0001, 1000.0);
    let mut view_matrix: Matrix4<f32> = Matrix4::look_at(view_eye, view_center, view_up);
    let mut model_matrix: Matrix4<f32> =
        Matrix4::from_translation(Vector3::new(-size_x as f32 / 2.0, 0.0, -size_z as f32 / 2.0));

    // per increment rotation
    let rotation = Matrix4::from(Quaternion::from(Euler {
        x: deg(0.0),
        y: deg(0.01),
        z: deg(0.0),
    }));

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    print!("{} instances\n", translations.len());

    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~ RENDER LOOP ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    let mut run = true;
    utils::loop_with_report(|_| {

        view_matrix = view_matrix * Matrix4::from_translation(Vector3::new(0.0, 0.0, 0.0));

        if run {
            model_matrix = rotation * model_matrix;
        }

        let uniforms = uniform! {
			perspective_matrix: Into::<[[f32; 4]; 4]>::into(perspective_matrix),
			view_matrix:        Into::<[[f32; 4]; 4]>::into(view_matrix),
			model_matrix:       Into::<[[f32; 4]; 4]>::into(model_matrix),

            atlas_texture: &atlas_texture,
            atlas_side:    atlas_side as u32,
        };

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        //    draw cubes
        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        use glium::Surface;
      //  let mut target = ctx.display().draw();
      //  target.clear_color_and_depth((0.0, 0.0, 1.0, 1.0), 1.0);

   //     target.draw((&cube.vertices, instance_attr.per_instance().unwrap()),
   //               &cube.indices,
   //               &program,
   //               &uniforms,
   //               &params)
   //         .unwrap();

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        //    draw axis
        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   //     axis_plot.draw(&mut target, &uniforms);

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        //    new context 
        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        use renderer::context::DrawSurface;
        let frame = DrawSurface::frame_begin(&ctx)
                        .draw(&axis_plot, &uniforms)
                        //.draw_with_program(&cube, &program)
                    .frame_end();

   //     ctx.draw(&axis_plot);
   //     ctx.draw_with_program(&cube, &program);

        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        //    finish frame
        // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

     //   target.finish().unwrap();

        // listing the events produced by the window and waiting to be received
        let mut resizes = Vec::new();
        {
            let events = ctx.display().poll_events();
            for ev in events {

                use glium::glutin::Event;
                use glium::glutin::ElementState;

                match ev {
                    Event::Closed => std::process::exit(0),  // the window has been closed 
                    Event::KeyboardInput(_, 9, _) => std::process::exit(0),  // esc
                    Event::KeyboardInput(ElementState::Released, 65, _) => run = !run,
                    Event::KeyboardInput(_, x, _) => print!("key {}\n", x),
                    Event::Resized(w, h) => resizes.push((w,h)),
                    _ => (),
                }
            }
        }
        
        // can not change window while context is borrowed
        for (w, h) in resizes{
            ctx.resize(w,h);
        }

    }, 5); // refresh every 5 secs

}
